/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class AppColorido extends javax.swing.JFrame {

    /**
     * Creates new form AppColorido
     */
    public AppColorido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpColorido = new javax.swing.JDesktopPane();
        mmbColorido = new javax.swing.JMenuBar();
        mmuPaletaCores = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mmiAzul = new javax.swing.JMenuItem();
        mmiVermelho = new javax.swing.JMenuItem();
        mmiSair = new javax.swing.JMenuItem();
        mmuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicativo Colorido");

        mmuPaletaCores.setText("Arquivo");
        mmuPaletaCores.add(jSeparator1);

        mmiAzul.setText("Azul");
        mmiAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiAzulActionPerformed(evt);
            }
        });
        mmuPaletaCores.add(mmiAzul);

        mmiVermelho.setText("Vermelho");
        mmiVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiVermelhoActionPerformed(evt);
            }
        });
        mmuPaletaCores.add(mmiVermelho);

        mmiSair.setText("Sair");
        mmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiSairActionPerformed(evt);
            }
        });
        mmuPaletaCores.add(mmiSair);

        mmbColorido.add(mmuPaletaCores);

        mmuAjuda.setText("Ajuda");
        mmbColorido.add(mmuAjuda);

        setJMenuBar(mmbColorido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpColorido, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpColorido, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exibirJanela(JInternalFrame janela){
        
        if(janela instanceof Vermelho){
            janela.setTitle("Vermelho Bolchevick");
        }else {
            janela.setTitle("Azul Banana");
        }
        
        //add objeto na interface
        dtpColorido.add(janela);
        
        // exibindo janela
        janela.show();
    }
    
    
    
    private void mmiAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiAzulActionPerformed
        // TODO add your handling code here:
        
        //chamada do método exibir janela
        this.exibirJanela(new Azul());
        
        // criação e instância do objeto da classe azul
        //Azul azul = new Azul();
        
        //add o objeto na classe
        //dtpColorido.add(azul);
        
        // exibindo objeto colorido
        //azul.show();
    }//GEN-LAST:event_mmiAzulActionPerformed

    private void mmiVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiVermelhoActionPerformed
        // TODO add your handling code here:
        
        // chamada do método exibir janela
        this.exibirJanela(new Vermelho());
        
        // criação e instancia do objeto da classe vermelho
        //Vermelho ver = new Vermelho();
        
        //add o objeto na classe
        //dtpColorido.add(ver);
        
        // exibindo objeto colorido
        //ver.show();
    }//GEN-LAST:event_mmiVermelhoActionPerformed

    private void mmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiSairActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Quer mesmo sair jão", "Sair", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_mmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppColorido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppColorido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpColorido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mmbColorido;
    private javax.swing.JMenuItem mmiAzul;
    private javax.swing.JMenuItem mmiSair;
    private javax.swing.JMenuItem mmiVermelho;
    private javax.swing.JMenu mmuAjuda;
    private javax.swing.JMenu mmuPaletaCores;
    // End of variables declaration//GEN-END:variables
}
